server:
  port: 0

spring:
  application:
    name: auth-service
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/auth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    prefix: 'Bearer '

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/