server:
  port: 8080

spring:
  application:
    name: api-gateway
  component-scan:
    base-package: com.srishti.gateway.filter

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-service
          predicates:
            - Path=/api/v1/auth/**

        - id: template-service
          uri: lb://TEMPLATE-service
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

urls:
  validate: http://localhost:8080/api/v1/auth/validate